# Generated by Django 6.0.2 on 2026-02-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='candidate',
            name='candidate_c_email_d848fc_idx',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='Extracted from CV by AI. Null if not found.', max_length=254, null=True),
        ),
    ]
