# Generated by Django 6.0.2 on 2026-02-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_remove_candidate_candidate_c_email_d848fc_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available'), ('open_to_offers', 'Open to Offers')], db_index=True, default='not_available', max_length=20),
        ),
    ]
