# Generated by Django 6.0.2 on 2026-03-04 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_alter_candidate_availability_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='The upload batch this candidate belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='candidate.candidateuploadbatch'),
        ),
    ]
