# Generated by Django 6.0.2 on 2026-04-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_candidate_contacts_emailed_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='name_without_surname',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Given name / first name only (no surname), from AI data_extracted.name', max_length=255),
        ),
    ]
