# Generated by Django 6.0.2 on 2026-04-27 19:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_candidate_name_without_surname'),
        ('organization', '0003_alter_organization_gender_alter_organization_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateToOrganizationsSubmissionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='The email address it was sent to.', max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_logs', to='candidate.candidate')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_submissions', to='organization.organizationcontact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_submissions', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Candidate Submission Log',
                'verbose_name_plural': 'Candidate Submission Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='candidate_c_status_869ccc_idx'), models.Index(fields=['candidate', 'contact'], name='candidate_c_candida_798f17_idx')],
            },
        ),
    ]
