# Generated by Django 6.0.2 on 2026-04-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_candidatetoorganizationssubmissionlog'),
        ('organization', '0003_alter_organization_gender_alter_organization_phase'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='candidatetoorganizationssubmissionlog',
            constraint=models.UniqueConstraint(fields=('candidate', 'contact'), name='unique_candidate_contact_submission'),
        ),
    ]
