"""
Django settings for edukai project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# ---------------------------
# Helper parsers for env vars
# ---------------------------
def env_bool(val, default=False):
    if val is None:
        return default
    return str(val).lower() in ("true", "1", "yes", "y", "on")


def env_int(val, default=0):
    try:
        return int(val)
    except (TypeError, ValueError):
        return default


def env_list(val, default=None, sep=","):
    if val is None or val == "":
        return default or []
    return [v.strip() for v in str(val).split(sep) if v.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-0d+6r(+du+wi_xq^7(n)vf1$nxb&$#-8l66&kk=jz66*zb#$)v")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool(os.getenv("DEBUG"), default=True)

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    # Add third-party apps here
    'rest_framework',                                   # Django Rest Framework
    "rest_framework_simplejwt",
    'rest_framework_simplejwt.token_blacklist',         # For logout functionality
    'drf_spectacular',                                  # DRF Documentation
    'corsheaders',                                      # CORS handling
]

LOCAL_APPS = [
    # Add local apps here
    "account",
    "organization",
]

INSTALLED_APPS += THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',            # CORS middleware should be high up
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'edukai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'edukai.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"


MEDIA_URL = os.getenv("MEDIA_URL", "/media/")
MEDIA_ROOT = Path(os.getenv("MEDIA_ROOT", str(BASE_DIR / "media")))


AUTH_USER_MODEL = os.getenv("AUTH_USER_MODEL", "account.User")


CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = env_list(
    os.getenv("CORS_ALLOWED_ORIGINS"),
    default=[
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]
)


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'account.authentication.CookieJWTAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    "EXCEPTION_HANDLER": "account.authentication.custom_exception_handler",
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=env_int(os.getenv("SIMPLE_JWT_ACCESS_TOKEN_HOURS"), 1)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=env_int(os.getenv("SIMPLE_JWT_REFRESH_TOKEN_DAYS"), 7)),
    'ROTATE_REFRESH_TOKENS': env_bool(os.getenv("SIMPLE_JWT_ROTATE_REFRESH_TOKENS"), True),
    'BLACKLIST_AFTER_ROTATION': env_bool(os.getenv("SIMPLE_JWT_BLACKLIST_AFTER_ROTATION"), True),

    "AUTH_HEADER_TYPES": ("Bearer",),       # If changing to "JWT", Then header must be: Authorization: JWT <access_token>
    "USER_ID_FIELD": "id",                  # UUID primary key
    "USER_ID_CLAIM": "user_id",

    "AUTH_COOKIE_ACCESS": "access_token",   
    "REFRESH_COOKIE_NAME": "refresh_token",
    "REFRESH_COOKIE_PATH": "/api/auth",
}


SPECTACULAR_SETTINGS = {
    'TITLE': os.getenv("SPECTACULAR_TITLE", 'EduKai APIs'),
    'DESCRIPTION': os.getenv("SPECTACULAR_DESCRIPTION", 'API documentation for EduKai - CV automation engine'),
    'VERSION': os.getenv("SPECTACULAR_VERSION", '1.0.0'),
    'SERVE_INCLUDE_SCHEMA': env_bool(os.getenv("SPECTACULAR_SERVE_INCLUDE_SCHEMA"), False),
}


# Redis cache (use django-redis)
REDIS_URL = os.getenv("REDIS_URL", "redis://127.0.0.1:6379/1")
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # "PASSWORD": os.getenv("REDIS_PASSWORD", ""),  # if needed
        }
    }
}


APP_NAME = os.getenv("APP_NAME", "EduKai")


PASSWORD_RESET_OTP_LENGTH = env_int(os.getenv("PASSWORD_RESET_OTP_LENGTH"), 6)
PASSWORD_RESET_OTP_TTL = env_int(os.getenv("PASSWORD_RESET_OTP_TTL"), 600)           # 10 min
PASSWORD_RESET_VERIFIED_TTL = env_int(os.getenv("PASSWORD_RESET_VERIFIED_TTL"), 600) # 10 min
PASSWORD_RESET_RESEND_COOLDOWN = env_int(os.getenv("PASSWORD_RESET_RESEND_COOLDOWN"), 60)  # 1 min
PASSWORD_RESET_MAX_REQUESTS_PER_HOUR = env_int(os.getenv("PASSWORD_RESET_MAX_REQUESTS_PER_HOUR"), 5)
PASSWORD_RESET_MAX_VERIFY_ATTEMPTS = env_int(os.getenv("PASSWORD_RESET_MAX_VERIFY_ATTEMPTS"), 5)
PASSWORD_RESET_OTP_PEPPER = os.getenv("PASSWORD_RESET_OTP_PEPPER", "change-this-in-production")


DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@edukai.com")
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = env_int(os.getenv("EMAIL_PORT"), 587)
EMAIL_USE_TLS = env_bool(os.getenv("EMAIL_USE_TLS"), True)
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")